# fly.toml app configuration file generated for jm-web-development on 2023-06-01T13:44:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jm-web-development"
primary_region = "dfw"

[http_service]
  internal_port = 8080
  processes = ["app"]
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[env]
  PORT = 8080